AWSTemplateFormatVersion: 2010-09-09
Description: "AWS with dynamoDB"

Parameters: 
  awsNumber:
    Description: AWS number
    Type: String

Resources: 
  booksRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "books-repository"
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - !Sub "arn:aws:iam::${awsNumber}:user/dev-limited" #TODO change who is allowed here, Should be your git task that will push and pull
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
