# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build, test, sign and package a WPF or Windows Forms desktop application
# built on .NET Core.
# To learn how to migrate your existing application to .NET Core,
# refer to https://docs.microsoft.com/en-us/dotnet/desktop-wpf/migration/convert-project-from-net-framework
#
# To configure this workflow:
#
# 1. Configure environment variables
# GitHub sets default environment variables for every workflow run.
# Replace the variables relative to your project in the "env" section below.
#
# 2. Signing
# Generate a signing certificate in the Windows Application
# Packaging Project or add an existing signing certificate to the project.
# Next, use PowerShell to encode the .pfx file using Base64 encoding
# by running the following Powershell script to generate the output string:
#
# $pfx_cert = Get-Content '.\SigningCertificate.pfx' -Encoding Byte
# [System.Convert]::ToBase64String($pfx_cert) | Out-File 'SigningCertificate_Encoded.txt'
#
# Open the output file, SigningCertificate_Encoded.txt, and copy the
# string inside. Then, add the string to the repo as a GitHub secret
# and name it "Base64_Encoded_Pfx."
# For more information on how to configure your signing certificate for
# this workflow, refer to https://github.com/microsoft/github-actions-for-desktop-apps#signing
#
# Finally, add the signing certificate password to the repo as a secret and name it "Pfx_Key".
# See "Build the Windows Application Packaging project" below to see how the secret is used.
#
# For more information on GitHub Actions, refer to https://github.com/features/actions
# For a complete CI/CD sample to get started with GitHub Action workflows for Desktop Applications,
# refer to https://github.com/microsoft/github-actions-for-desktop-apps

name: cloudformation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Blibliotheque.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Publish
    - name: Publish
      run: dotnet publish --output ./artifact/publish ../Blibliotheque/Blibliotheque/Blibliotheque.csproj

    # AWS cred
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Copy cloudformation Template
    - name: copy cloudformation Template
      run: cp ../Blibliotheque/deployment.yaml ./artifact/deployment.yaml

    # Copy Docker Template
    - name: copy Docker Template
      run: cp ../Blibliotheque/Dockerfile ./artifact/Dockerfile
    
    # Copy Docker Template
    - name: copy Docker Template
      run: cp ../Blibliotheque/awsec2.yaml ./artifact/awsec2.yaml

    # Upload Artifiact
    - uses: actions/upload-artifact@v4
      with:
        name: books
        path: ./artifact

    
        
  deploy-ecr:
    runs-on: ubuntu-latest
    env:
      Solution_Name: Blibliotheque.sln 
    needs: build
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Download artifact
      - uses: actions/download-artifact@v5
        with:
          name: books
          path: artifact
            
      # AWS cred
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # AWS deploy cloud formation
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: booksStacks
          template: artifact/deployment.yaml
          parameter-overrides: "awsNumber=${{ secrets.awsNumber }}"
          no-fail-on-empty-changeset: "1"
      
      # AWS buil and Push docker in ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: books-repository
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{env.REGISTRY}}/${{env.REPOSITORY}}:${{env.IMAGE_TAG}} .
          docker push ${{env.REGISTRY}}/${{env.REPOSITORY}}:${{env.IMAGE_TAG}}
          docker build -t ${{env.REGISTRY}}/${{env.REPOSITORY}}:latest .
          docker push ${{env.REGISTRY}}/${{env.REPOSITORY}}:latest
  
  deploy-ec2:
    runs-on: ubuntu-latest
    needs: deploy-ecr
    steps:
      # Download Artifact
      - uses: actions/download-artifact@v5
        with:
          name: books
          path: artifact
      
      # AWS cred
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # AWS deploy cloud formation for ec2
      - name: Deploy to AWS ec2
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ec2Stacks
          template: artifact/awsec2.yaml
          parameter-overrides: "DockerImage=${{ secrets.DOCKER_IMAGE }}"
          no-fail-on-empty-changeset: "1"

      # AWS ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      # Pull image and run
      - name: Pull image and run
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: books-repository
          IMAGE_TAG: ${{ github.sha }}
        uses: chris5451/aws-ecr-run-image@main
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          account_id: ${{ secrets.awsNumber }}
          repo: ${{env.REPOSITORY}}
          region: ${{ secrets.AWS_REGION }}
          tag: latest
          name: ${{env.REGISTRY}}/${{env.REPOSITORY}}
          port: 5254
